### ISSUE TITLE
Unable to connect to scyall 4.6

### ISSUE THREAD

**Issue by akshaypatidar1999** [scylladb/java-driver#161]
Getting following exception when connecting to scylla `4.6.8-0.20220919.0aa9a8c26`.
```An exception occurred while executing the Java class. Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=10.20.6.135:9042, hostId=null, hashCode=395c0470): [com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|connecting...] Protocol initialization request, step 1 (OPTIONS): failed to send request (java.nio.channels.NotYetConnectedException)] ```

Scylla java driver version: `4.7.2.0`.

Scylla server config
```
cluster_name: 'test-scylla-cluster'
num_tokens: 16
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.20.163.165,10.20.6.135,10.20.156.90"
listen_address: 10.20.6.135
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 1000
#authenticator: PasswordAuthenticator
#authorizer: CassandraAuthorizer
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 10.20.6.135
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
hinted_handoff_enabled: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
